name: Deploy to Server

on:
  push:
    branches: [master]

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.x'
      
      - name: Build
        run: |
          go build -o myapp .
      
      - name: Upload binary
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "myapp"
          target: "/home/deployuser/app"

      - name: Restart app and update openai_api_key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo 'export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}' >> ~/.bashrc
            sudo systemctl restart myapp
